Change code styles to agreed settings
greyfoxit/java-code-styles pull request #2
Opened 2017-06-06 22:11 UTC by bnucci

This should take care of #1

2017-06-06 22:27 UTC, radekkozak commented
Looks ok, i'll give it a go on a live codebase if it will not do sth weird or unexpected with what we already got i think we'll be good to go

I'll try to clean the codebase hand in hand with RxNetwork project to see

2017-06-06 22:35 UTC, radekkozak requested changes
Ok, i think you forgot to rename the settings internally (within xml itself) so it doesn't appear in Intellij as Greyfox but rather as Square :)

2017-06-06 22:38 UTC, radekkozak submitted a review, later dismissed

2017-06-06 22:38 UTC, radekkozak commented on configs/codestyles/GreyfoxAndroid.xml
>  <code_scheme name="SquareAndroid">
here

2017-06-07 09:46 UTC, bnucci commented on configs/codestyles/GreyfoxAndroid.xml
>  <code_scheme name="SquareAndroid">
done

2017-06-07 11:24 UTC, radekkozak approved these changes
I think we're good to 🚢 

In few rare instances we're gonna need to use Intellij `@formatter:on/off` (ie long generic params - don't think there is a setting for that anyway in code style)

2017-06-07 11:27 UTC, merged